training_pipeline_config:
  pipeline_name: textSummarizer
  artifact_dir: artifact



data_ingestion_config:
  dataset_download_url: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  zip_data_dir: zip_data
  ingested_dir: ingested_data



data_validation_config:
  status_file: status.txt
  all_required_files: ["train", "test", "validation"]


data_transformation_config:
  tokenizer_name: google/pegasus-cnn_dailymail
  transformed_dir: transformed_data



  
model_trainer_config:
  model_name: google/pegasus-cnn_dailymail
  



model_evaluation_config:
  
